# Generated by Django 4.2.15 on 2024-10-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='doctor',
        ),
        migrations.AddField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='record_details',
            field=models.TextField(default='No details available'),
        ),
    ]
